### PR TITLE
Fix for php artisan cache:clear to work again

### PR DESCRIPTION
**Pull request by guillermobt**
Fixes the "CommandNotFoundException" error when you try to clear the cache with:
php artisan cache:clear

### CODE REVIEW

**Review by xtcat — COMMENTED** [review]
I dont think your problem is related to this plugin.

Do you have the \Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class loaded in your providers list?

**Comment by guillermobt** [comment]
Yes, I do have it loaded (please, see attached picture)

The fact is that, following your instructions, if I comment the line:
`// Illuminate\Cache\CacheServiceProvider::class,`
the "cache:clear" command dissapears.

Note: I'm using Laravel 5.2

20180201_consolesupportserviceprovider-is-loaded

**Comment by guillermobt** [comment]
The code added in the commit is copied from the `Illuminate\Cache\CacheServiceProvider` class. 
As the instructions for this plugin says to comment that line in the providers section of the `config/app.php` file, we are losing the functionality (the command to clear the cache). 

At least, this is true for Laravel versions from 5.0 to 5.3 as you can see in the Laravel API docs: 
https://laravel.com/api/5.2/Illuminate/Cache/CacheServiceProvider.html#method_registerCommands 

This changed in Laravel 5.4 
https://laravel.com/api/5.4/Illuminate/Cache/CacheServiceProvider.html

So I will be adding a Laravel version check to the code so it only registers the cache related console commands if Laravel version is < 5.4

**Comment by xtcat** [comment]
Ah yes, you are correct.

I will create a <5.4 compatible branch, and the master will support => 5.5

**Comment by guillermobt** [comment]
Sorry, didn't intend to reflect newer modifications in my fork as commits here :-P 
I closed the p-r as you're creating a compatible branch for versions < 5.4. 
Thanks.

**Pull request closed without merging**
